name: Build and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to AWS ECR
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REPOSITORY_URI: ${{ vars.REPOSITORY_URI }}
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

      - name: Build Docker image
        env:
          ECR_REPOSITORY_URI: ${{ vars.REPOSITORY_URI }}
        run: |
          echo "Building Docker Image..."
          TAG="${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}"
          IMAGE_FULL_NAME="${{ github.repository }}:${TAG}"
          docker build -t $ECR_REPOSITORY_URI/$IMAGE_FULL_NAME .
          docker push $ECR_REPOSITORY_URI/$IMAGE_FULL_NAME
          echo $IMAGE_FULL_NAME > image_full_name.txt
          echo ${{ github.ref_name }} > target_branch.txt

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image_full_name
          path: image_full_name.txt

      - name: Save target branch
        uses: actions/upload-artifact@v4
        with:
          name: target_branch
          path: target_branch.txt

  deploy_argocd:
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-latest
    needs: build_docker_image
    environment: ${{ github.ref_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: image_full_name

      - name: Download target branch
        uses: actions/download-artifact@v4
        with:
          name: target_branch

      - name: Set up Git
        run: |
          git config --global user.email "rdi.devops"
          git config --global user.name "rdi.devops"

      - name: Update Kubernetes Deployment
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          ECR_REPOSITORY_URI: ${{ vars.REPOSITORY_URI }}
        run: |
          IMAGE_FULL_NAME=$(cat image_full_name.txt)
          TARGET_BRANCH=$(cat target_branch.txt)
          echo "Cloning repository..."
          git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/diogoab/gitops-test.git
          cd gitops-test
          echo "Updating deployment image..."
          yq -i '.spec.template.spec.containers[0].image = "'$ECR_REPOSITORY_URI'/'$IMAGE_FULL_NAME'"' k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Update deployment image to $IMAGE_FULL_NAME"
          git push origin main